\c demos
insert into hawq.customer (select * from hcatalog.hive.customer);
insert into hawq.customer_address (select * from hcatalog.hive.customer_address);
insert into hawq.customer_demographics (select * from hcatalog.hive.customer_demographics);
insert into hawq.date_dim (select * from hcatalog.hive.date_dim);
insert into hawq.household_demographics(select * from hcatalog.hive.household_demographics);
insert into hawq.income_band (select * from hcatalog.hive.income_band);
insert into hawq.inventory (select * from hcatalog.hive.inventory);
insert into hawq.item (select * from hcatalog.hive.item);
insert into hawq.item_marketprices (select * from hcatalog.hive.item_marketprices);
insert into hawq.product_reviews (select * from hcatalog.hive.product_reviews);
insert into hawq.promotion (select * from hcatalog.hive.promotion);
insert into hawq.reason (select * from hcatalog.hive.reason);
insert into hawq.ship_mode (select * from hcatalog.hive.ship_mode);
insert into hawq.store (select * from hcatalog.hive.store);
insert into hawq.store_returns (select * from hcatalog.hive.store_returns);
insert into hawq.store_sales (select * from hcatalog.hive.store_sales);
insert into hawq.time_dim (select * from hcatalog.hive.time_dim);
insert into hawq.warehouse (select * from hcatalog.hive.warehouse);
insert into hawq.web_clickstreams (select * from hcatalog.hive.web_clickstreams);
insert into hawq.web_page (select * from hcatalog.hive.web_page);
insert into hawq.web_returns (select * from hcatalog.hive.web_returns);
insert into hawq.web_sales (select * from hcatalog.hive.web_sales);
insert into hawq.web_site (select * from hcatalog.hive.web_site);