\c demos
insert into hawq.customer (select * from hcatalog.hive.customer);
insert into hawq.customer_address (select * from hcatalog.hive.customerAddress);
insert into hawq.customer_demographics (select * from hcatalog.hive.customerDemographics);
insert into hawq.date_dim (select * from hcatalog.hive.date_dim);
insert into hawq.household_demographics(select * from hcatalog.hive.householdDemographics);
insert into hawq.income (select * from hcatalog.hive.income);
insert into hawq.inventory (select * from hcatalog.hive.inventory);
insert into hawq.item (select * from hcatalog.hive.item);
insert into hawq.item_marketprices (select * from hcatalog.hive.marketprices);
insert into hawq.product_reviews (select * from hcatalog.hive.reviews);
insert into hawq.promotion (select * from hcatalog.hive.promotion);
insert into hawq.reason (select * from hcatalog.hive.reason);
insert into hawq.ship_mode (select * from hcatalog.hive.shipMode);
insert into hawq.store (select * from hcatalog.hive.store);
insert into hawq.store_returns (select * from hcatalog.hive.storeReturns);
insert into hawq.store_sales (select * from hcatalog.hive.storeSales);
insert into hawq.time_dim (select * from hcatalog.hive.timeDim);
insert into hawq.warehouse (select * from hcatalog.hive.warehouse);
insert into hawq.web_clickstreams (select * from hcatalog.hive.webClickstreams);
insert into hawq.web_page (select * from hcatalog.hive.webPage);
insert into hawq.web_returns (select * from hcatalog.hive.webReturns);
insert into hawq.web_sales (select * from hcatalog.hive.webSales);
insert into hawq.web_site (select * from hcatalog.hive.webSite);